### ISSUE TITLE
Windows default Notepad stopped working after using option Y

### ISSUE THREAD

**Issue by wyf32222** [ionuttbara/windows-defender-remover#102]
I am on Windows 11 22H2
After I run the exe with option Y and rebooting
the default windows notepad.exe is not working  i.e. when opening a file with notepad nothing shows up (no process in task manager)
checked system32 folder and notepad.exe is still there

it is not a big deal since I have sublime text and notepad++ installed
but just let you know option Y might affect other windows default apps i guess

**Comment by Aetopia** [comment]
The Y option has been cleared noted with that it can break Windows Update and UWP apps.

**Comment by ionuttbara** [comment]
use U option. 
Y removes C:\Program Data\Microsoft\Windows Defender and if you belive or not, this folder is needed for work with UWP and Windows App SDK Apps. i specified in release section there.

**Comment by wyf32222** [comment]
ok my bad i never check release section but only readme
