### ISSUE TITLE
Is it possible to remove defender without other changes?

### ISSUE THREAD

**Issue by zyr3344** [ionuttbara/windows-defender-remover#103]
When I used the y method of 12.6 in 23h2, all software I opened was forced to open directly as an administrator. When searching for applications such as Task Manager, a new one called "View system resource usage in Task Manager" appeared. Can these strange changes be manually reverted?

**Comment by Aetopia** [comment]
The Y option has been cleared noted with that it can break Windows Update and UWP apps.

**Comment by ionuttbara** [comment]
you can remove WinDefend and Wd* (it can be Windows Defender Network and Windows Defender boot drivers) like in safe method.. you can find in [HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services] section. backup first, remove and reboot.
