### ISSUE TITLE
Does this work on Windows 10 LTSC 2019 ?

### ISSUE THREAD

**Issue by filamento** [ionuttbara/windows-defender-remover#106]
Hi everyone,

I've downloaded the latest version 12.6 and rebooted my computer (Windows 10 x64 LTSC 2019) in safe mode.

Under safe mode, I've run DefenderRemover.exe and chose option N

Then a bunch of CMD windows quickly popped up, REGEDIT window also popped up and after a few seconds the computer restarted automatically.

I've disabled safe mode and rebooted to normal mode. Defender seems to be disabled, but I find something very strange.

All its services (MsSecCore, wscsvc, WdNisDrv, etc) are still present in the registry. And many of them still have a value of 0 in "Start", which means they will be autostarted by windows!

Why does this happen? Shouldn't those services be removed from the registry? Or shouldn't they at least be disabled (start=4) ??

**Comment by ionuttbara** [comment]
yes the services will be removed from register together with defender antivirus and security files after that it reboots because you can't stop the antivirus service when your PC is on.
