### ISSUE TITLE
Is This Normal

### ISSUE THREAD

**Issue by KasdeyaHoolheyak** [ionuttbara/windows-defender-remover#107]
When I run it it disables control panel features like UAC, and most computer management tools are permanently gone including user and disk management. With my lock screen wallpaper and all my start menu programs, btw.

**Comment by ionuttbara** [comment]
disablation of UAC is normal because its disabling LUA. but user and disk management is not normal. noted as bug.

**Comment by ionuttbara** [comment]
ok, this is due a bug in 12.5.7 where i removing content from program data. fixed since 12.5.8.
