### ISSUE TITLE
win10 LTSC use it will cause Start Button error

### ISSUE THREAD

**Issue by bb33bb** [ionuttbara/windows-defender-remover#110]
win10 LTSC use it will cause Start Button error

**Comment by ionuttbara** [comment]
what version of Windows 10 LTSC are you using? i am trying to simulate..

**Comment by bb33bb** [comment]
![image](https://github.com/ionuttbara/windows-defender-remover/assets/5463104/4346a60b-5069-4c61-846b-61df3d975245)

**Comment by bb33bb** [comment]
I tried again and this time there is no issue
Maybe because I upgraded the sys.
I am going to close this issue and if there is going to be absolute issue for sure,  I will reopen it again.

> what version of Windows 10 LTSC are you using? i am trying to simulate..

**Comment by ionuttbara** [comment]
thx for providing. i dont test ltsc but the y options and all safe methods working without problems 😅
