### ISSUE TITLE
it did literally nothing other than opening a bunch of cmds without commands and regedit

### ISSUE THREAD

**Issue by Lemon553311-dev** [ionuttbara/windows-defender-remover#112]
as said in title
Latest windows 11
shouldn't you run some commands?

**Comment by ionuttbara** [comment]
Can you write whay button had you pressed before to start the cmd and regedit?
Maybe its a problem with GetTrustedInstaller, rolling back to PowerRun it solve issues.

**Comment by Lemon553311-dev** [comment]
I used the button U (safe thingy) - disable windows defender and security components

(Eitherway i just used the delete function so cant do more testing)

**Comment by abbaccadd0** [comment]
> Can you write whay button had you pressed before to start the cmd and regedit? Maybe its a problem with GetTrustedInstaller, rolling back to PowerRun it solve issues.

I got same problem.
I press (N) for disabling Defender and Security Components (safe)
It display mulit CMD and regedit, but no command is run in them

**Comment by m1st333** [comment]
same issue. Tried on a fresh windows

**Comment by ionuttbara** [comment]
for N and M methods its a problem and noted as lastest release.
stay tuned.

**Comment by Lemon553311-dev** [comment]
Any update on this?

((((I used to use a website called Bing rewards farmer as an alternative
and it doesn't work for some reason (likely Microsoft put up some
restriction/filter on types of searches) )))).

 Is this project no longer maintained?

вт, 19 дек. 2023 г., 17:05 FranDJ99 ***@***.***>:

**Comment by ionuttbara** [comment]
is maintained. but waiting for installation of cumulative updates in Windows 11 22H2 its get harder, modifying commands and etc.
the best part these problems are from Windows 11 PCs which are a bit problematic for me, and some devs =). some issues can take longer.. but for this is caused by the GetTrustedInstaller, which is implemented. because this is opensource i will try to adapt into the script and takes a bit longer.

**Comment by Lemon553311-dev** [comment]
Whoops sorry I somehow thought this was a different thread 😅

ср, 20 дек. 2023 г., 14:55 Ionuț Bara ***@***.***>:

**Comment by abbaccadd0** [comment]
> is maintained. but waiting for installation of cumulative updates in Windows 11 22H2 its get harder, modifying commands and etc. the best part these problems are from Windows 11 PCs which are a bit problematic for me, and some devs =). some issues can take longer.. but for this is caused by the GetTrustedInstaller, which is implemented. because this is opensource i will try to adapt into the script and takes a bit longer.

Maybe try [MinSudo](https://github.com/M2Team/NanaRun) to run script with TrustedInstaller permissions?
GetTrustedInstaller hasn't been updated in a long time.

**Comment by ionuttbara** [comment]
i put /k instead /c in cmd command. and thats why it showed so many windows of cmd in remover menu. modified in 12.6.3.
