### ISSUE TITLE
My Securety Center was Buggy

### ISSUE THREAD

**Issue by Marvin700** [ionuttbara/windows-defender-remover#114]
This Fixed it for me:

https://answers.microsoft.com/en-us/windows/forum/all/windows-security-center-service-has-been-removed/47b55525-f0be-4434-95c3-265fbba64807

**Comment by ionuttbara** [comment]
what method you used?

**Comment by Marvin700** [comment]
I think it was disabling the Defender + Security Center.

**Comment by ionuttbara** [comment]
ok. noted as bug. working today and tommorow for next version. stay tuned.

**Comment by ionuttbara** [comment]
i seen this and security center was removed, so your bug listing is not taken to be a bug anymore. this is closed.
