### ISSUE TITLE
Spotted No-op line and some trivial syntax issues.

### ISSUE THREAD

**Issue by rdebath** [ionuttbara/windows-defender-remover#115]
https://github.com/ionuttbara/windows-defender-remover/blob/741baf8738450d6a2aaa51fa953d0719793d9e5a/Remover/REGS/Antivirus_d.reg#L30-L33

I would guess there's a `"value"=dword:00000000 ` missing here.

Also the syntax highlighting doesn't like this line: Too many digits
https://github.com/ionuttbara/windows-defender-remover/blob/741baf8738450d6a2aaa51fa953d0719793d9e5a/Remover/REGS/Antivirus_d.reg#L38-L39
https://github.com/ionuttbara/windows-defender-remover/blob/741baf8738450d6a2aaa51fa953d0719793d9e5a/Remover/REGS/DisableDefenderPolicies.reg#L98-L99

**Comment by ionuttbara** [comment]
thx for providing updated the code.
i updated the git, but will be in next version of the app.
