### ISSUE TITLE
my system is messed up after used "-U"

### ISSUE THREAD

**Issue by merenguesL** [ionuttbara/windows-defender-remover#117]
1. The system's built-in search function cannot be used
2. Microsoft Store installation program reported all errors
3. wsl cant open，docker engine not able to run
4. Unable to reset system, "No changes made"
5."Settings" opens slowly, even unable to open at all
actually there are more problems......the whole computer turns to be insanely slow

**Comment by merenguesL** [comment]
oh,from win11 23H2

**Comment by ionuttbara** [comment]
noted as bug.

**Comment by enoxitus** [comment]
same thing happened to me, is there any fix to it?

**Comment by ionuttbara** [comment]
i will check, if i get same results, i will apply a fix and also i write here an workaround, after writing the workaround the issue will be closed.

**Comment by enoxitus** [comment]
> i will check, if i get same results, i will apply a fix and also i write here an workaround, after writing the workaround the issue will be closed.

thank you, I appreciate it! if it helps, I was using build 22621

**Comment by Lemon553311-dev** [comment]
> same thing happened to me, is there any fix to it?

I just factory reset my system ¯\_(ツ)_/¯ forgot the restore point.

**Comment by Minedeployder** [comment]
Yeah, same for me. System is so messed up now. Half of applications malfunction, microsoft store, xbox etc wont open even after reinstall. I just want to delete defender, not entire system, come on!

**Comment by ylmw0131** [comment]
> 4\. Unable to reset system, "No changes made"
>     5."Settings" opens slowly, even unable to open at all
>     actually there are more problems......the whole computer turns to be insanely slow

cool, my system is malfunction as same as you.

**Comment by ionuttbara** [comment]
deprecated method.
