### ISSUE TITLE
Use PowerShell to download & run the latest version in real time.

### ISSUE THREAD

**Issue by 1014982466** [ionuttbara/windows-defender-remover#118]
## Expected behavior (if you have any solution write here.)

Considering the small size of this software and the necessity of always keeping the latest version, it is recommended to consider using PowerShell to get the latest version every time you run it, like massgravel/Microsoft-Activation-Scripts.

## Other Comments
See: https://github.com/massgravel/Microsoft-Activation-Scripts/releases
Method 1 - PowerShell (Recommended)

**Comment by ionuttbara** [comment]
thanks for sugestion.. i removed the exe way for Edge Remover and OneDrive Remover which are 100% powershell now. maybe into another version i try do to that.. there its a catch i don't know how to integrate RunAsTi into script.

**Comment by ionuttbara** [comment]
for defender remover this is not planned now.
