### ISSUE TITLE
Microsoft store won't download or update apps after removing defender

### ISSUE THREAD

**Issue by sanjarbek-ismatov** [ionuttbara/windows-defender-remover#119]
## *What* affects the bug ?

Microsoft Store

## *When* does this occur?

When I want to download or update apps

## *In which* version of Windows does this issue happen ? Write version complete.

Windows 10 home (10.0.19045.3803)

## Other Comments
I tried it in windows  10 and 11 several times. Whenever I remove defender and security components, Store won't work. I was just going to disable them, but it didn't work at all. Now I removed defender and SC, How can I fix Microsoft store? Even after clicking update apps, apps which is being updated won't be updated and work any more unless I reset them with settings

![image](https://github.com/ionuttbara/windows-defender-remover/assets/65501439/6a72b471-369e-4aaa-b37a-057395eae63b)
![image](https://github.com/ionuttbara/windows-defender-remover/assets/65501439/b7c8ef61-f930-4b04-9062-551d93ace953)

**Comment by Lemon553311-dev** [comment]
Can confirm

**Comment by ionuttbara** [comment]
closed. dupilcate of #83 .
