### ISSUE TITLE
Disabling Defender and Security Component doesn't work.

### ISSUE THREAD

**Issue by iiwwnnaa** [ionuttbara/windows-defender-remover#120]
## *What* affects the bug ?

I disabled Defender and Security Components but it has no effect on me.

## *When* does this occur?

1. Enter Safe Mode
2. Run Script and Press N
3. Reboot
4. Defender and Security Components are still alive. (nothing is changed)

## *In which* version of Windows does this issue happen ? Write version complete.

WIN10 PRO 22H2 

## Expected behavior (if you have any solution write here.)

Defender and Security Component should be disabled.

**Comment by iiwwnnaa** [comment]
12.5.6 version is working, however it doesn't work on latest version.

**Comment by tikkamasalla** [comment]
> 12.5.6 version is working, however it doesn't work on latest version.

Sadly it just appears it is, but it is not really working. Windows forced updated me like you, and ever since then neither the latest or 12.5.6 versions work to disable it. 

Proof is this: 

Run the powershell command: Get-MpComputerStatus


![image](https://github.com/ionuttbara/windows-defender-remover/assets/104959287/e831201b-aedc-4f95-90cb-04a09760f60b)

![image](https://github.com/ionuttbara/windows-defender-remover/assets/104959287/a9bf37d0-eaab-4efc-8bf4-e01f804abde7)

**Comment by sulisu** [comment]
The algorithm is correct is correct. Maybe the implementation is not compatible with some windows version.

Windows 10 Home 22H2, neither 12.6.3 or 12.5.6 works.

In normal windows mode, I manually modify and run the command from batch to disable defender and smartscreen and it works.

I can change task schedule and import reg with admin privilege.

I can not rename "C:\Windows\System32\smartscreen.exe", windows alerts that the trustedinstaller right is necessory. But `GetTrustedInstaller.exe cmd.exe /k move /y "C:\Windows\System32\smartscreen.exe" "C:\Windows\System32\smartscreen.plm"` in the batch file doesn't work.

`GetTrustedInstaller.exe "C:\Windows\System32\cmd.exe /k move /y C:\Windows\System32\smartscreen.exe C:\Windows\System32\smartscreen.plm"` works.

reference to the readme in <https://github.com/rara64/GetTrustedInstaller>

**Comment by touhamii** [comment]
i cant watch 4k videos without drops anymore thnx to windows defender , 
https://i.imgur.com/fHxrRCx.png
this script doesnt work i remember in the past it worked

**Comment by Aranak** [comment]
It's doesn't work for me too, the code broke when it open the registry with 2 black windows open plus the starting one. 

The antimalware service executable is still there after restart even after the executable say the process have been successful. 
I gone to safe mode as instructed and used Disabling Defender and Security Component option and came back of safe mode as instructed.

I try to use administrator mode for the executable to be sure. I have Windows 10 Pro, Version 22H2, OS build 19045.3930

**Comment by iiwwnnaa** [comment]
Huh
Close the issue without any comment? Intersting.

**Comment by ionuttbara** [comment]
the tool part is deprecated, so the safe methods are not anymore.
so the tool will focus for removal defender, and not for disable/enable defender.
read last release changelog first.
