### ISSUE TITLE
Most of my applications disappeared (Is it normal?)

### ISSUE THREAD

**Issue by Comeonnoob** [ionuttbara/windows-defender-remover#128]
## *What* happened?
As described in the title, most of my apps and even Windows system apps disappeared after using this tool

## Windows version:
Windows 10 Home, build 18363.535

## *How* to replicate:
When choosing to removing both Defender and it's security components (Y) on this app
The C:\ProgramData\Microsoft\Windows\Start Menu\Programs folder is empty after restarting

## Expected behavior (my solution)
Nothing is supposed to happen to C:\ProgramData\Microsoft\Windows\Start Menu\Programs folder
Used a restore point to revert it back

![Untitled](https://github.com/ionuttbara/windows-defender-remover/assets/140257029/dbec31bd-b952-43e9-9c8a-0325c0ec21f7)

**Comment by ionuttbara** [comment]
ok. that's wrong usage of GetTrustedInstaller. reverting to powerrun after script rewriting.

**Comment by ionuttbara** [comment]
fixed in 12.6.9, but you cannot recover files back.
