### ISSUE TITLE
Notepad and most troubleshooting tools don't work

### ISSUE THREAD

**Issue by zhangqian543** [ionuttbara/windows-defender-remover#129]
I used the Y option, which caused problems with these functions. I couldn't view pictures and couldn't use Notepad. Please tell me how to solve it. I didn't use a system restore point.

version 12.6.3

Windows 11 home 22H2  22621.3007

**Comment by ionuttbara** [comment]
test 12.6.9 now.

**Comment by zhangqian543** [comment]
No, I just want to know how to restore my notepad and picture viewer

**Comment by zhangqian543** [comment]
Or you tell me what he deleted and I'll find a solution.

**Comment by ionuttbara** [comment]
maybe its uwp, try to uninstall the packages from settings and reinstall again from microsoft store.
<a href="https://apps.microsoft.com/detail/9MSMLRH6LZF3?hl=en-US&gl=US"> Download Notepad </a>

<a href="https://apps.microsoft.com/detail/9WZDNCRFJBH4?hl=en-US&gl=US"> Download Photo Viewer</a>
