### ISSUE TITLE
Script Continues Even When You Answer "N"

### ISSUE THREAD

**Issue by adrianmmiller** [ionuttbara/windows-defender-remover#130]
always nice to see a script hose your system even when you tell it not to, and then as a bonus restart without any warning at the end of it

would not recommend this script

**Comment by 5aad666** [comment]
man same happened to me 
this is so bad update

**Comment by ionuttbara** [comment]
fixed in 12.7, pressing another keys which are not 'Y' or 'y' the script will close.
also, added a warning in the script which says about the reboot.
