### ISSUE TITLE
While downloading my AV software reported viruses

### ISSUE THREAD

**Issue by whitst** [ionuttbara/windows-defender-remover#133]
C:\Users\Stevie Wonder\AppData\Local\Vivaldi\User Data\Default\Cache\Cache_Data\f_000103=>windows-defender-remover-main/PowerRun.exe Trojan.GenericKD.69234797 Deleted 
C:\Users\Stevie Wonder\windows-defender-remover\.git\objects\pack\pack-ecfe378920d80aee304efc62b0dc43208e131fd8.pack=>(blob pack) Heur.BZC.PZQ.Boxter.81.B13728E8 Cleaned

**Comment by clicky6** [comment]
> C:\Users\Stevie Wonder\AppData\Local\Vivaldi\User Data\Default\Cache\Cache_Data\f_000103=>windows-defender-remover-main/PowerRun.exe Trojan.GenericKD.69234797 Deleted C:\Users\Stevie Wonder\windows-defender-remover.git\objects\pack\pack-ecfe378920d80aee304efc62b0dc43208e131fd8.pack=>(blob pack) Heur.BZC.PZQ.Boxter.81.B13728E8 Cleaned

This is in FAQ, It's a false positive
https://github.com/ionuttbara/windows-defender-remover#-why-is-the-downloaded-executable-being-flagged-as-a-virus
