### ISSUE TITLE
Disabling UAC/LUA should not done by default

### ISSUE THREAD

**Issue by nopeless** [ionuttbara/windows-defender-remover#134]
Related

#104 
#107

@ionuttbara First of all, thanks for maintaining the repo

I think this section is outside the scope of removing windows defender and should be a separate script that some users can manually opt into

I'm raising this issue because I am advocating for removing this functionality

At the very least, I am very curious about the rationale for disabling uac/lua. Thanks in advance

**Comment by ionuttbara** [comment]
you can put in batch all that to enable. Normally i will add this into Q&A Section.
```
reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f
reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorUser /t REG_DWORD /d 3 /f
reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorAdmin /t REG_DWORD /d 3 /f
```
put this in .bat file and restart.

**Comment by ionuttbara** [comment]
note for next versions: separate removal of antivirus and security components.

**Comment by nopeless** [comment]
Thanks, it wasn't hard to find out how to revert the changes. I'm glad you are considering my suggestion

**Comment by ionuttbara** [comment]
Defender Remover 12.8 will do this thing. For now i wil release 12.7.2 to end the annoying bug with Microsoft Store on Windows 11. Stay tuned.
arguments or keywords:

Y or y - removes all
A or a - removes antivirus
S or S - removes security elements.

Please note: When you remove antivirus, the Antimalware GUI of Windows Security will be also removed. and Windows Security App will show all elements except antivirus protection.
