### ISSUE TITLE
0x8D053CF3 - Microsoft Store Apps not work

### ISSUE THREAD

**Issue by epikaigle444** [ionuttbara/windows-defender-remover#136]
![image](https://github.com/ionuttbara/windows-defender-remover/assets/61425652/71e8f990-aff1-4b7c-a71b-cccf35273981)
I've had this message since installation
Version 23H2 (OS Build 22631.3155) with Release 12.7

**Comment by JayBeeAre** [comment]
Just discovered this as well. Windows doesn't want to update either. Have you found a temp solution?

**Comment by clicky6** [comment]
For me the apps are downloading & installing through Microsoft Store, but they are not uninstalling.
![image](https://github.com/ionuttbara/windows-defender-remover/assets/89839714/23c8c3d3-af86-468e-b22b-2e3a6c96d7ab)

I applied the latest version of this script a few days ago only & To try to fix this, I followed all the steps on https://www.guidingtech.com/fix-app-removal-failed-error-0x80073cfa-in-windows-11/ except SFC and DISM as I think they could bring back Microsoft Defender/Security & also the clean boot step still it is not working.

**Comment by playaz44** [comment]
I can confirm, version 12.7 of the script break Microsoft store and creates random problems with explorer.exe (sometimes it does not turn on, there is a black screen and only a Taskmanager works). Installation with keeping data not working, the Defender icon is restored but it cannot be turned on, and the applications and Microsoft store does not work anymore. The only solution is complete reinstall system.

**Comment by clicky6** [comment]
> I can confirm, version 12.7 of the script break Microsoft store and creates random problems with explorer.exe (sometimes it does not turn on, there is a black screen and only a Taskmanager works). Installation with keeping data not working, the Defender icon is restored but it cannot be turned on, and the applications and Microsoft store does not work anymore. The only solution is complete reinstall system.

I think it is turning off UAC which is interfering with the installing & uninstalling of Microsoft Store apps.

**Comment by playaz44** [comment]
> > I can confirm, version 12.7 of the script break Microsoft store and creates random problems with explorer.exe (sometimes it does not turn on, there is a black screen and only a Taskmanager works). Installation with keeping data not working, the Defender icon is restored but it cannot be turned on, and the applications and Microsoft store does not work anymore. The only solution is complete reinstall system.
> 
> I think it is turning off UAC which is interfering with the installing & uninstalling of Microsoft Store apps.

I turned UAC on to the default level, restarted the computer and nothing changed, the store doesn't work, I can't enter the start menu, Windows Defender still can't start.

**Comment by clicky6** [comment]
> > > I can confirm, version 12.7 of the script break Microsoft store and creates random problems with explorer.exe (sometimes it does not turn on, there is a black screen and only a Taskmanager works). Installation with keeping data not working, the Defender icon is restored but it cannot be turned on, and the applications and Microsoft store does not work anymore. The only solution is complete reinstall system.
> > 
> > 
> > I think it is turning off UAC which is interfering with the installing & uninstalling of Microsoft Store apps.
> 
> I turned UAC on to the default level, restarted the computer and nothing changed, the store doesn't work, I can't enter the start menu, Windows Defender still can't start.

Same here, I also turned on UAC still Microsoft Apps are not installing or uninstalling.
