### ISSUE TITLE
DefenderRemover.exe Silent Options ?

### ISSUE THREAD

**Issue by freeload101** [ionuttbara/windows-defender-remover#137]
## *What* affects the bug ?
using the DefenderRemover.exe I have no idea what args to pass to make it silent ?  /R what ? 
I want to add this to my debloat ps1 script https://github.com/freeload101/SCRIPTS/blob/master/Windows_Powershell_ps/Win10Hardening_Debloat.ps1

**Comment by ionuttbara** [comment]
```DefenderRemover.exe y``` OR 
```DefenderRemover.exe Y```
