### ISSUE TITLE
Search in start menu stopped working after update

### ISSUE THREAD

**Issue by acurvers** [ionuttbara/windows-defender-remover#144]
## *What* affects the bug ?
Search in start menu

## *When* does this occur?
after update 2024-02 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5034848)

## *In which* version of Windows does this issue happen ? Write version complete.
2024-02 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5034848)

## *How* do we replicate the issue?
update 2024-02 Cumulative Update Preview for Windows 11 Version 23H2 for x64-based Systems (KB5034848)

## Expected behavior (if you have any solution write here.)
you type when have the start menu open or in the search box of the start menu, expected is search results from the start menu, what happens is the start menu closes and nothing happens

**Comment by acurvers** [comment]
uninstalling the update doesnt help

**Comment by nook86** [comment]
also here same issue search and main menu

**Comment by nxyoo** [comment]
Same here, tried everything, DISM, SFC Scan, fixing windows but it does nothing

**Comment by ionuttbara** [comment]
> yeah i reinstalled windows to fix it. This defenderremover should be taken offline and releasing stopped until this is fixed, peoples windows gets bricked also atleast the windowsremover should prompt first to create a windows restore point @ionuttbara

added a prompt of creation of System Restore point.

Windows search is working, is not broken.  Tested in 4 systems and i don t get it. Do you use Windows Insider?

**Comment by shiner66** [comment]
Broken also for me

**Comment by acurvers** [comment]
yeah why is this issue marked closed .. its still an issue

**Comment by ionuttbara** [comment]
ok. i will check that later today again,

**Comment by riccardonuzz** [comment]
Same problem here. Microsoft app store does not update any app (can't even do it manually in PowerShell). Search works for me but every windows app is broken (photos, notepad, spotify, ecc). Winget doesnt work either

**Comment by ionuttbara** [comment]
> Same problem here. Microsoft app store does not update any app (can't even do it manually in PowerShell). Search works for me but every windows app is broken (photos, notepad, spotify, ecc). Winget doesnt work either

and this issue had happened after you updating windows with that update? what version of Defender Remover had you downloaded?

**Comment by Vulturezzzx** [comment]
> > Same problem here. Microsoft app store does not update any app (can't even do it manually in PowerShell). Search works for me but every windows app is broken (photos, notepad, spotify, ecc). Winget doesnt work either
> 
> and this issue had happened after you updating windows with that update? what version of Defender Remover had you downloaded?

This happens to me as well. I installed and executed defenderremover about a month ago. (version 12.7) I had to completely reset one of my pcs because it was completely unusable, I need notepad and other microsoft store apps for work. Im hoping I dont have to reset my other pc because I have important stuff on here, but I might have to if there is no fix. please look into it and let me know if you need any more info

**Comment by Vulturezzzx** [comment]
> > Same problem here. Microsoft app store does not update any app (can't even do it manually in PowerShell). Search works for me but every windows app is broken (photos, notepad, spotify, ecc). Winget doesnt work either
> 
> and this issue had happened after you updating windows with that update? what version of Defender Remover had you downloaded?

also it didnt happen after a windows update, it started happening a couple of weeks ago when I restarted my pc,.

**Comment by nook86** [comment]
Any chances for fix , menu is broken also search button, or I have to reinstall my fresh windows again and use again with windows defender :-(

**Comment by icyhoty2k** [comment]
same issue 23h2

**Comment by ionuttbara** [comment]
will be fixed in next version !

**Comment by icyhoty2k** [comment]
after some work while everithing is normal mouse cannot right click on some menu while in other it clicks mostly uwp apps stop working . it happen at random times , the only fix is to restart , or log out and then log in back . How to fix this its killing productivity ???????

**Comment by RickyWong19922005** [comment]
How to repair without reinstall windows?

**Comment by annarana** [comment]
I'm having problems too, Microsoft Store and all the apps not working and windows in general is super unstable. I got a black screen after the last update. I tried to uninstall it but I can't cause the release 12.7.2 doesn't have an option to activate defender again, and tried 12.5 version but it doesn't work. Can anybody help me uninstall it cause my computer is very unstable right now, and I don't know what to do. Many thanks

**Comment by RickyWong19922005** [comment]
> I'm having problems too, Microsoft Store and all the apps not working and windows in general is super unstable. I got a black screen after the last update. I tried to uninstall it but I can't cause the release 12.7.2 doesn't have an option to activate defender again, and tried 12.5 version but it doesn't work. Can anybody help me uninstall it cause my computer is very unstable right now, and I don't know what to do. Many thanks

Reinstall windows...

**Comment by kbxu** [comment]
For those who don't want to reinstall windows, the below two commands can fix the start-menu search issue, but right click on toolbar menu's icon still shows nothing...
run as administrator one by one in cmd:

```
DISM.exe /Online /Cleanup-image /Restorehealth
sfc /scannow
```

ref: [Using System File Checker in Windows](https://support.microsoft.com/en-us/windows/using-system-file-checker-in-windows-365e0031-36b1-6031-f804-8fd86e0ef4ca)
