### ISSUE TITLE
Spotlight Issue

### ISSUE THREAD

**Issue by Cabus1982** [ionuttbara/windows-defender-remover#145]
## *What* affects the bug ?
Spotlight Lock Screen.

## *When* does this occur?
After the system reboot.

## *In which* version of Windows does this issue happen ? Write version complete.
Windows 10 Pro 22H2 (1000.19054.1000.0)

## *How* do we replicate the issue?
Just run the program to delete the Defender and restart.

## Expected behavior (if you have any solution write here.)
Be able to have a functional, informative and dynamic lock screen.

## Other Comments
Screenshot
![Untitled](https://github.com/ionuttbara/windows-defender-remover/assets/28199465/8a0ef63d-6b97-44d6-bc31-06fc2ee78c56)

**Comment by ionuttbara** [comment]
i will check this.
Defender Remover does not have 
ConfigureWindowsSpotlight option this is interesting bug which i will check.
