### ISSUE TITLE
Some items are not deleted

### ISSUE THREAD

**Issue by xmha97** [ionuttbara/windows-defender-remover#148]
Some items are not deleted:

![image](https://github.com/ionuttbara/windows-defender-remover/assets/23485114/820ba61e-cf39-4fc1-bcfd-497bc4e88425)

https://learn.microsoft.com/en-us/sysinternals/downloads/autoruns

**Comment by ionuttbara** [comment]
At the services, things are not removed because of an protection which cannot be bypass by TrustedInstaller.
But the task scheduler and contextmenu handlers this must be a bug.

**Comment by ionuttbara** [comment]
it must be fixed in 12.8.
