### ISSUE TITLE
go back, is it possible?

### ISSUE THREAD

**Issue by gabri25ele** [ionuttbara/windows-defender-remover#154]
once the automatic script is run, if I need to go back and re-enable in the future, is there a script or method to do this? 
I don't think I saw it in the FAQ.

**Comment by lbj-007** [comment]
Similarly, I would like to know how to undo the removal after executing it. Now I find that this tool is not effective, and many files have been isolated. I can't access the original entry to restore them.

**Comment by annarana** [comment]
I second this too. My windows is bricked, my taskbar is gone, I can't access to any apps from the microsoft store, I can't use the shortcuts on my trackpad. Please make a script the re enable windows defender, because I don't want to reset windows and all of my programs again.

**Comment by ionuttbara** [comment]
> once the automatic script is run, if I need to go back and re-enable in the future, is there a script or method to do this? I don't think I saw it in the FAQ.

not possible. you can restore if you created system restore before. the ideea to create re-enabling in the future its making patchable by microsoft and its bad =).

btw.. working for a new version which limits the removal only antivirus, like older versions but some security components have dependency so its a bit hard.

**Comment by gabri25ele** [comment]
Can't you re-enable things that are disabled? 
so some things are actually removed? 
Isn't it possible to reinstall them?

**Comment by ionuttbara** [comment]
if you done upgrade in-place or reinstalling a clean windows. i said there:

> > once the automatic script is run, if I need to go back and re-enable in the future, is there a script or method to do this? I don't think I saw it in the FAQ.
> 
> not possible. you can restore if you created system restore before. the ideea to create re-enabling in the future its making patchable by microsoft and its bad =).
> 
> btw.. working for a new version which limits the removal only antivirus, like older versions but some security components have dependency so its a bit hard.

**Comment by gabri25ele** [comment]
I meant for example with powershell. if I uninstall something, I can always reinstall it.

**Comment by ionuttbara** [comment]
i keep this issue on until i will solve this. thx for providing infos.

**Comment by ionuttbara** [comment]
i will close this because there's one thing:

the script is removing defender. trying to develop ways to made re-enable and more versatible, but i donțt recommend that because sometimes its get patchable and the script will not work.

i tried to make with one scope: to kill defender, not to restore. if you have bugs such windows system functionaliity was broken by the app, you'll feel free to write into a new issue. If you want to restore Defender after you apllied the remover, this app is not for you.

**Comment by gabri25ele** [comment]
do you think it is possible to disable the **Antimalware Service Executable** separately?

**Comment by ionuttbara** [comment]
> do you think it is possible to disable the **Antimalware Service Executable** separately?

yes. but its temporary , after 2 or 3 restarts sgrmbroker and  Windows Security Service (needed to run SecHealthUI and more core components) are re enabling.
