### ISSUE TITLE
YO! what is this?

### ISSUE THREAD

**Issue by rrha** [ionuttbara/windows-defender-remover#156]
https://www.virustotal.com/gui/file/9caa9d970f801818ebf71838c7338d726bdd70fc7cac343bdb21512c3bd6ceaa

**Comment by doggeddalle** [comment]
when the normie doesn't understand PUPs

**Comment by ionuttbara** [comment]
its from .exe file and multiple problems in detection are into that. 
so if you download the source and scan it its safe.
