### ISSUE TITLE
I ran the  DefenderRemover.exe 12.8.0 and used option [C]

### ISSUE THREAD

**Issue by XeonG** [ionuttbara/windows-defender-remover#163]
...instant restart after 10seconds.. that is stupid (where is the user choice in that??!) 

and after restart a windows update (this was already a nag from microshite but I sometimes shutdown/restart without running the update this tool just ignored that and allowed microshite to install whatever crapware update they had)

And to top it off it seems the antimalware spyware infested shite service went full blown retard and was consuming 100% cpu after restart.. .not something I was expecting from running this tool
![Taskmgr_LwNtXPlYasdYi](https://github.com/ionuttbara/windows-defender-remover/assets/1556183/145a2e90-a662-4498-ad61-d2d9d355f54c)

disabling the realtime fucking useless waste of cpu protection crap has since stopped... but for long.. hopefully this time, it doesn't manage to turn itself back on and chew cpu on doing useless background snivelling shit..., wish linux desktop wasn't such garbage and could at least get to windows xp levels of usability and features...

rant ended

**Comment by ionuttbara** [comment]
the 'C' option i not exist in defender remover.
the current options are 'Y' - remove defender + disable security mitigations, 'A' - remove defender 'S' - disable all mitigations. re-run the app and try one of these.
