### ISSUE TITLE
Everything started is now as an Administrator

### ISSUE THREAD

**Issue by XeonG** [ionuttbara/windows-defender-remover#165]
How can I disable this, there are certain programs that don't work well like Unity when run as Administrator and it seems since running this tool apps like Unity are being started in Administrator mode. Last thing run was this tool and its changed some settings that need reverting or an option of disabling

**Comment by XeonG** [comment]
I made the change to that setting but it has made no difference, previously my setting for UAC was the very lowest and I never had this issue of everything starting up in Admininstrator mode before this [DefenderRemover.exe](https://github.com/ionuttbara/windows-defender-remover/releases/download/release_def_12_8/DefenderRemover.exe) from this repo  ...so it is something else this tool has changed that has messed things up somewhere... any other ideas?

there was a windows update that got ran at the restart of this tool being run aswel.... but I doubt mmsuck would do an update to cause apps to start in admin mode, so I'm thinking its this tool that changed a setting?

**Comment by AndnixSH** [comment]
that's weird. For me, reverting UAC back to default makes a difference. I only tried it on Win11 ARM running in VM on my Mac mini

**Comment by ionuttbara** [comment]
put these in a command prompt and UAC will work again.
forgot to make separately. sorry. 😊
the option for you is 'A' not 'Y'

```
reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f
reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorUser /t REG_DWORD /d 3 /f
reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorAdmin /t REG_DWORD /d 3 /f
```

**Comment by CyberLykan** [comment]
> put these in a command prompt and UAC will work again. forgot to make separately. sorry. 😊 the option for you is 'A' not 'Y'
> 
> ```
> reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f
> reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorUser /t REG_DWORD /d 3 /f
> reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorAdmin /t REG_DWORD /d 3 /f
> ```

I made those changes but everything still wants to run in administrator mode.

I also tried reverting the changes made by windows-defender-remover/Remove_SecurityComp/DisableLSAProtection.reg with values from a fresh Windows install (and removing the added keys if they are not present in the fresh Windows install), but that did not fix the issue either.

**Comment by XeonG** [comment]
yeah none of those reg changes made any difference still getting things start in admininstrator

**Comment by XeonG** [comment]
> > put these in a command prompt and UAC will work again. forgot to make separately. sorry. 😊 the option for you is 'A' not 'Y'
> > ```
> > reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f
> > reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorUser /t REG_DWORD /d 3 /f
> > reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorAdmin /t REG_DWORD /d 3 /f
> > ```
> 
> I made those changes but everything still wants to run in administrator mode.
> 
> I also tried reverting the changes made by windows-defender-remover/Remove_SecurityComp/DisableLSAProtection.reg with values from a fresh Windows install (and removing the added keys if they are not present in the fresh Windows install), but that did not fix the issue either.
> 
> I'm also using Unity like OP.

damn same issues .. yeah hope get a solution to this its a bit annoying and I don't feel like doing a full system wipe right now to fix it.

**Comment by CyberLykan** [comment]
> > > put these in a command prompt and UAC will work again. forgot to make separately. sorry. 😊 the option for you is 'A' not 'Y'
> > > ```
> > > reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f
> > > reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorUser /t REG_DWORD /d 3 /f
> > > reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorAdmin /t REG_DWORD /d 3 /f
> > > ```
> > 
> > 
> > I made those changes but everything still wants to run in administrator mode.
> > I also tried reverting the changes made by windows-defender-remover/Remove_SecurityComp/DisableLSAProtection.reg with values from a fresh Windows install (and removing the added keys if they are not present in the fresh Windows install), but that did not fix the issue either.
> > I'm also using Unity like OP.
> 
> damn same issues .. yeah hope get a solution to this its a bit annoying and I don't feel like doing a full system wipe right now to fix it.

My apologies, I looked at the wrong file. It should be windows-defender-remover/Remove_SecurityComp/**_DisableUAC.reg_**
I got confused thinking LSA was a typo for LUA.
Changing the values mentioned in that file back to the defaults seems to have fixed the issue.

**Comment by ionuttbara** [comment]
reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v EnableLUA /t REG_DWORD /d 0 /f
reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorUser /t REG_DWORD /d 3 /f
reg.exe ADD HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System /v ConsentPromptBehaviorAdmin /t REG_DWORD /d 3 /f

these.

**Comment by XeonG** [comment]
Does it require a restart as I still got the issue after running that.. .also despite running the tool I still have this microshit running 

![Taskmgr_5PRnNPgVQN](https://github.com/ionuttbara/windows-defender-remover/assets/1556183/62f0b198-c74c-4b36-8818-6a7c5ce29536)

**Comment by xuestrange** [comment]
same issue, but solved by https://github.com/ionuttbara/windows-defender-remover/issues/120 and https://github.com/ionuttbara/windows-defender-remover/issues/165#issuecomment-2133935272

@XeonG hope to help u.

**Comment by Big-Daddio** [comment]
had the same problem here...

_In conjunction with_ a couple of restarts **and** also adjusting the UAC slider back to normal, this post with the registry entries seems to have sorted it.  The reg entries alone did not work for me...
[https://github.com/ionuttbara/windows-defender-remover/issues/165#issuecomment-2133935272](url)

I must say though, this is a heck of a security risk to introduce without anyone being forewarned.  Some folks (admittedly not likely those using a script like this) may not appreciate the security aspect and think nothing of it...   

Assuming this is a bug happening for everyone, it should probably be fixed pronto, or at least the remediation provided above should be integrated into the package...
