### ISSUE TITLE
Antimalware Service Executable still runs

### ISSUE THREAD

**Issue by Ch0i10** [ionuttbara/windows-defender-remover#166]
## *What* affects the bug ?
Windows Defender Security App.

## *When* does this occur?
When using windows

## *In which* version of Windows does this issue happen ? Write version complete.
Windows 11 23h2 pro 22631.3593

## *How* do we replicate the issue?
When opening task manager

## Expected behavior (if you have any solution write here.)
Antimalware service executable should not be running

![11686_05-29-24](https://github.com/ionuttbara/windows-defender-remover/assets/132732273/410e2a1e-96c9-457b-874d-ce9a7aecc522)

**Comment by zlsq** [comment]
same bug

**Comment by Ch0i10** [comment]
> same bug

i managed to fix it by also removing mitigations

**Comment by Sswozy** [comment]
> i managed to fix it by also removing mitigations

How do you fix it?
I'm searching online and not finding any help really D:

**Comment by Ch0i10** [comment]
> > i managed to fix it by also removing mitigations
> 
> How do you fix it? I'm searching online and not finding any help really D:

just run win defender remover again then remove both defender + mitigations

**Comment by Sswozy** [comment]
> > > i managed to fix it by also removing mitigations
> > 
> > 
> > How do you fix it? I'm searching online and not finding any help really D:
> 
> just run win defender remover again then remove both defender + mitigations

i added DisableAntiSpyware and it worked!

**Comment by Sswozy** [comment]
i fixed it by putting DisableAnitSpyware

**Comment by Andy-45** [comment]
same here, but fixed it by running the script twice

**Comment by vadimk1337** [comment]
> same here, but fixed it by running the script twice

+1

**Comment by ionuttbara** [comment]
run again the script. the app is working. if not, disable realtime protection and tamper protection and run it again.

**Comment by fahri314** [comment]
The solution is here: <https://github.com/ionuttbara/windows-defender-remover/issues/204>
