### ISSUE TITLE
[Suggestion] New Method for Safely Disabling Windows Defender (reversible) - Safe for Windows Update and Microsoft Store Functionality

### ISSUE THREAD

**Issue by IRedDragonICY** [ionuttbara/windows-defender-remover#171]
best for from "clean install", here are steps to safely disable Windows Defender without impacting Windows Update or the Microsoft Store:

1. Begin by turning off real-time malware protection in Windows Defender.

2. Modify specific Group Policies to prevent Windows Defender from reactivating after updates:
![image](https://github.com/ionuttbara/windows-defender-remover/assets/98265563/715c2f4a-f7b7-4dab-82de-0da44630c8ff)

3. Disable windows defender service like WinDefend, webthreat or other things (can use powerun or TrustedInstaller) . for SmartScreen can disable with just rename.

By following these steps, you can update your system without encountering errors, as security intelligence updates will still be applied while Windows Defender remains disabled.

It can be an idea for creating a new script to disable windows defender next.

**Comment by ionuttbara** [comment]
yes and no.
deployed DisableAntiSpyware value in previous versions of the script, and its removed in 12.7.x because is not working anymore on Windows build 15063 or newer


Not recommend revertible methods because its getting patched somehow via Windows Update. (if that are policy/registry)
