### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by wind91283** [ionuttbara/windows-defender-remover#173]
Hi, So basically I ran the exe with the option A but after that my pc reset and it worked fine as in the defender was off and it was all I asked for but **some programs that need to run as administrator do not open at all** and I pretty much need some of them but I can't run them anymore since I ran the defender remover, Is there an option to revert this since I didn't create a restore point and if there's not.. is there any fix for my issue?

**Comment by ionuttbara** [comment]
```
[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System]
"EnableLUA"=dword:00000001
"ConsentPromptBehaviorAdmin"=dword:00000003
"ConsentPromptBehaviorUser"=dword:00000003
"EnableUIADesktopToggle"=dword:00000001
"ValidateAdminCodeSignatures"=dword:00000001
"EnableSecureUIAPaths"=dword:00000001
"PromptOnSecureDesktop"=dword:00000001
```

add this into reg file and reboot. This it will enable UAC. Also this will be added into UAC enable in FAQ Section.
