### ISSUE TITLE
Left over

### ISSUE THREAD

**Issue by axbender** [ionuttbara/windows-defender-remover#183]
Not bug, just a "technical debt"...

The entries at HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\WMI\Autologger\Def* are not removed.

**Comment by ionuttbara** [comment]
it does remove DefenderAuditLogger and DefenderApiLogger. Another entires are not removed because maybe had enabled WDAG. (Windows Defender Application Guard).
