### ISSUE TITLE
INACCESSIBLE_BOOT_DEVICE BSOD 

### ISSUE THREAD

**Issue by FluidExtractor** [ionuttbara/windows-defender-remover#185]
## *What* does the bug affect?
The ability to boot into Windows

## *When* does this occur?
After running the script with the "Remove Windows Defender Antivirus + Disable All Security Mitigations" option on a system with software RAID set up I can't get it to boot. 

## *In which* version of Windows does this issue happen ? Write version complete.
Windows 11 22H2

## Other Comments
I made a restore point prior to running the script but it's useless since Windows RE doesn't detect the Windows install.
The drives themselves are fine, since I can access them without problems after booting a separate Windows install from an external drive and installing AMD's RAID drivers. Considering that I can access the drives, I could try reverting the changes made by the script.  Although knowing which part of the script messed things up would be helpful.
Any help/ideas would be appreciated.

**Comment by FluidExtractor** [comment]
Okay so now I feel a bit stupid. I haven't thought about the possibility that Windows RE might now have the RAID drivers I need. After adding them to the WinRE image I managed to use the previously mentioned restore point. 
Still, something within the script might be breaking RAID configurations. Might be worth looking into.

**Comment by ionuttbara** [comment]
hm... noted as bug

**Comment by ionuttbara** [comment]
@FluidExtractor  can you name what is the name of .sys file of AMD RAID Drivers which you have? and what version if that is STOREMI or not?

**Comment by FluidExtractor** [comment]
@ionuttbara rcraid.sys rccfg.sys rcbottom.sys
![23_09_24_21 33_4](https://github.com/user-attachments/assets/bd891714-ee8e-4aeb-9f97-d029ed682a1c)
No StoreMI. I don't think it would benefit me in any way if I only have SSDs

**Comment by ionuttbara** [comment]
does not matter. i just want to know its STOREMI or not. working on fix. sorry for late response, i just switching the remover to powershell version, and make some fixes.
