### ISSUE TITLE
windows security giving a white screen

### ISSUE THREAD

**Issue by maximilien1990** [ionuttbara/windows-defender-remover#186]
hi, is it normal that after using this if i open windows security it gives a white blank screen and if in the search bar i click on virus threat protection instead i get page not available your it has disabled access to some areas of this app? and also aside from restore point is there a say to reactivate it??

thanks

**Comment by Eticeweng** [comment]
i got the same problem here, after removing and disabling the WS,
as mentioned, the script print out an error info right after the phrase`Removing UWP`
```
Edition	Windows 11 Pro
Version	23H2
Installed on	‎2022-‎10-‎22
OS build	22631.4460
Experience	Windows Feature Experience Pack 1000.22700.1047.0
```

**Comment by ionuttbara** [comment]
because is removed.  but in next version 12.8.2 will not disable the pages if defender is removed due the redundacy of the app.
