### ISSUE TITLE
How do I restore it?

### ISSUE THREAD

**Issue by baiyao105** [ionuttbara/windows-defender-remover#193]
After using the “Y” option of this tool, the removal of Defender affects many of microsoft's default programs such as photos, prompting the windows firewall to be turned off, but I didn't create a restore point, is there a way to do this other than using an iso image restore?

**Comment by juxty** [comment]
`sfc /SCANNOW` should fix this. If not, you can just do a windows update.

**Comment by baiyao105** [comment]
> `sfc /SCANNOW` should fix this. If not, you can just do a windows update.
Thanks, I've solved it with Windows Update.
