### ISSUE TITLE
Remove 


### ISSUE THREAD

**Issue by ghost** [ionuttbara/windows-defender-remover#200]
https://github.com/ionuttbara/windows-defender-remover/blob/main/Remove_defender_moduled%2FDisableDefenderPolicies.reg

**Comment by wefalltomorrow** [comment]
Why?

**Comment by ionuttbara** [comment]
not recommended. 
because in some 3rd antivirus applications will show Defender its working but it s not.
this file will NOT be removed. maybe stripped sometime.
