### ISSUE TITLE
Defender Remover v12.8.2 Breaks Network in 24H2

### ISSUE THREAD

**Issue by Wolfzzman** [ionuttbara/windows-defender-remover#201]
With a fresh install of 24H2 Pro 26100.1742 or above I had this problem.

I had to do this to get my network to work in the first place.
Local Group Policy Editor

Computer Configuration, Windows Settings, Security Settings, Local Policies, Security Options
Double click on Microsoft Network Client: Digitally sign communications (always)
Double click on Microsoft Network Client: Digitally sign communications (if server agrees)
Set both of these to "Disabled"
Click on OK.

Computer Configuration, Administrative Templates, Network, Lanman Workstation
Double click on "Enable Insecure Guest Logons"
Set this to "Enabled"
Click on OK.

Then after running Defender Remover v12.8.2 ([Y] Remove Windows Defender Antivirus + Disable All Security Mitigations) my network, stopped working and I could not access any of my other computers or my NAS Drivers anymore. I went back to Defender Remover v12.8.1 ([Y] Remove Windows Defender Antivirus + Disable All Security Mitigations) and all is working again.
I'm not sure what it broke.
I understand Microsoft has updated its security even more when it comes to sharing or seeing network drives in 24H2.
So maybe Defender is still relying on something that windows needs for the network to work. Who Knows?

I hope this can be sorted out for future updates as I’ve never had an issue with your program, and I love it. Thank You

**Comment by Scarlaid** [comment]
ah so its a global issue
seems like most of my UWP app just refused to open, even Microsoft Store itself, or simply trying to login with my microsoft account

Windows 11 Home 24H2
![image](https://github.com/user-attachments/assets/6fc03c7b-6dd1-40bb-9b0e-5d259977db5b)

**Comment by Scarlaid** [comment]
fixed the above, just re-register SmartScreen and repair Windows Store, back to normal

**Comment by ionuttbara** [comment]
hm... smartscreen issue again 🤔

maybe keeping smartscreen for microsoft store apps enabled, but its not a solution. the ``smartscreen.exe, smartscreen.dll and smartscreenps.dll`` are unregistered those crashes are rare, but good to investigate.
