### ISSUE TITLE
Guide: disable Antimalware Service Executable without Settings UI after Windows 11 24H2 update

### ISSUE THREAD

**Issue by gottagofaster236** [ionuttbara/windows-defender-remover#204]
After Windows 11 24H2 update Antimalware Service Executable reappeared again, but I couldn't access any of the Security settings because they were removed by this app. To disable Defender, I did the following:
1. Download PowerRun https://www.sordum.org/9416/powerrun-v1-7-run-with-highest-privileges/
2. Reboot Windows 11 to Safe Mode
3. In Safe Mode, open PowerRun and launch regedit through PowerRun with elevated privileges. After that disable the tamper protection registry key by setting its value to 0:
   ![image](https://github.com/user-attachments/assets/2db6a345-0d2b-484b-bdec-648534153dae)
4. Open group policy editor (Run, gpeditor.msc) and then enable the policy that disables Defender:
   ![image](https://github.com/user-attachments/assets/30b1f944-8f75-465e-b0e1-31a229d82166)
5. Reboot PC

**Comment by adn011** [comment]
ty goat !! 🙏😭✨
