### ISSUE TITLE
In build 25905, (Canary) you can't turn on or off or remove defender

### ISSUE THREAD

**Issue by ionuttbara** [ionuttbara/windows-defender-remover#68]
the script is not working in lastest canary build of windows.

**Comment by shilak1** [comment]
In build 25909 there is no such thing, there is 25905...

**Comment by jbara2002** [comment]
i've wrong, its 25905. Disabler and Classic is not working, and even UAC is not disabling.. so i will to wait a bit what happens to the platform. I'll provide some workarounds, about is needed to disable Microsoft Vulnerable Driver List (maybe IoBit Unlocker integration coming back?)

**Comment by ionuttbara** [comment]
Microsoft fixed the issue in build 25915. The issue is closed.
