### ISSUE TITLE
Silent Remover

### ISSUE THREAD

**Issue by jamiekarvans** [ionuttbara/windows-defender-remover#70]
Plz make silent remover, no cmd screen, no debug plz.
i have to install for alot of customers and the moment they see the cmd screen they get scared as if they're getting hacked or someting, so it just nice to have the option.

**Comment by ionuttbara** [comment]
you can run this into .bat script
``` cmd.exe /k start DefenderRemover.exe /Y ``` (or /N, /E etc.) for running in silent mode.
Documentation will be updated asap.
