### ISSUE TITLE
Remove history

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [ionuttbara/windows-defender-remover#71]
Start menu and apps list still remembers that there was Windows Defender (Windows Security UWP app) and no matter how hard I've tried, it doesn't let me to remove it from there. Is there any bloatware tool to completely remove it - not just it's services, but completely to be removed. The same thing I would also wanted for Microsoft Edge to save ny hardware resources.

**Comment by admin-elvistrujanovic** [comment]
If you have issues with permissions to successfully remove all files and registry and other things about that app, you know that you can always use for example AdvancedRun.exe to run some task as even TrustedInstaller on the latest version of any Windows (except Windows 7 and earlier of course 😅)

**Comment by ionuttbara** [comment]
> Start menu and apps list still remembers that there was Windows Defender (Windows Security UWP app) and no matter how hard I've tried, it doesn't let me to remove it from there. Is there any bloatware tool to completely remove it - not just it's services, but completely to be removed. The same thing I would also wanted for Microsoft Edge to save ny hardware resources.

So, you can use PowerRun , AdvancedRun to remove tasks and stop the services, but the switching from *classic* to *safe* removal and restore takes time. (Testing in Windows 10 ,and 11, testing in Insider Builds).
But if you want to remove all (including files, and more) you can try by pressing y (classical removal). In Windows 10 works without any problems, but in Windows 11 there are some changes to break the current installation of Windows which you had. But the script works fine from Windows 8 to Windows 11 258xx (because in build 25905 the methods which are disabling defender and remove are invalid, searching for solutions for now).
If you want to remove another apps such Edge or OneDrive check my profile, in repo for Edge and OneDrive Remover.
Also, if you want to debloat the system and optimize for maximum performance , by disabling telemetry and some services you can get Melody script Repo. Download last exe and un-zip it into location. After that choose what tweaks are needed for you.)

> If you have issues with permissions to successfully remove all files and registry and other things about that app, you know that you can always use for example AdvancedRun.exe to run some task as even TrustedInstaller to stop services, own their permissions and do the tasks on the latest version of any Windows (except Windows 7 and earlier of course 😅)

For now the permission are working fine in Defender Rmeover. Recently i've replaced PowerRun with nsudo (works fine for all specified version of Windows and its ok for now) single thing is to run as Admin for get effect in application.

**Comment by admin-elvistrujanovic** [comment]
> > Start menu and apps list still remembers that there was Windows Defender (Windows Security UWP app) and no matter how hard I've tried, it doesn't let me to remove it from there. Is there any bloatware tool to completely remove it - not just it's services, but completely to be removed. The same thing I would also wanted for Microsoft Edge to save ny hardware resources.
> 
> So, you can use PowerRun , AdvancedRun to remove tasks and stop the services, but the switching from *classic* to *safe* removal and restore takes time. (Testing in Windows 10 ,and 11, testing in Insider Builds).
> But if you want to remove all (including files, and more) you can try by pressing y (classical removal). In Windows 10 works without any problems, but in Windows 11 there are some changes to break the current installation of Windows which you had. But the script works fine from Windows 8 to Windows 11 258xx (because in build 25905 the methods which are disabling defender and remove are invalid, searching for solutions for now).
> If you want to remove another apps such Edge or OneDrive check my profile, in repo for Edge and OneDrive Remover.
> Also, if you want to debloat the system and optimize for maximum performance , by disabling telemetry and some services you can get Melody script Repo. Download last exe and un-zip it into location. After that choose what tweaks are needed for you.)
> 
> > If you have issues with permissions to successfully remove all files and registry and other things about that app, you know that you can always use for example AdvancedRun.exe to run some task as even TrustedInstaller to stop services, own their permissions and do the tasks on the latest version of any Windows (except Windows 7 and earlier of course 😅)
> 
> For now the permission are working fine in Defender Rmeover. Recently i've replaced PowerRun with nsudo (works fine for all specified version of Windows and its ok for now) single thing is to run as Admin for get effect in application.
> 

So if I understand correctly, the classic removal method that is called by "y" are not completely support on Windows 11 Insider Canary builds due to the high security provided by system so that even system while device is booted cannot write into some registry files and getting error (Access Denied).

You're working on a fix but that will take a while to finish some work for that thing (maybe you can make bootable usb tool that can have more permissions and access to the whole registry files no matter what security says by the system for example - and also searching for other parts of the commands to be sure that it will do the job is recommended too)

The another tool for tweaking Windows you provided have many features that can boost performance of the PC and remove bloatware apps but it still have the same issues about removing apps and etc... in latest Windows Insider Canary builda just like this tool

You also provided support for Edge and Onedrive removal but I don't think it will work fine on this insider build unfortunatelly based on the previous informations I've got


Did I understand correctly?

**Comment by ionuttbara** [comment]
Yes. 
Defender Remover was affected only in 25905 (Canary Build). in 25915, is working fine (maybe was a Microsoft Issue). Also disabling defender with policy it retains after reboot.
Melody Script is fine, you can try it, and Edge , OneDrive Removers too.
