### ISSUE TITLE
Please don't reboot the computer automatically by default

### ISSUE THREAD

**Issue by zdimension** [ionuttbara/windows-defender-remover#72]
This is an amazing script. It works perfectly.

But I ran it on my PC while I had open things in the background, a running VM, etc. After disabling WD (by pressing N), it said that a reboot was needed, and then a countdown appeared. I didn't really know what would happen after the countdown, I assumed the window would just close, but then it force-rebooted my PC. Programs were killed, my running VM was shut down ungracefully. Fortunately no data loss, but I still think this shouldn't happen. It reminds me of old driver install wizards from the early 00s that would reboot your computer automatically at the end, without asking you for confirmation first and without letting you close open programs.

**Comment by ionuttbara** [comment]
You can press *ctrl+c* and will not reboot.
Also you must start task  manager and open the explorer to get the desktop back.
you must know, the defender and windows security services will run upon to next reboot.

**Comment by zdimension** [comment]
This means running the script as is will still forcingly reboot the computer, it's not clear at all that this will happen when the script runs, this is the problem

Like, yes, I saw the countdown and that I could press Ctrl+C, it's simply that nowhere was it written that after the countdown all my running apps would be killed and my computer would hard reboot

The usual way scripts such as this one work is that by default an interactive choice is presented at the end, and a command-line flag can be passed ("/noninteractive", "/silent", "/y", ...) that tells the script to reboot automatically without user input
