### ISSUE TITLE
Antimalware Service Executable / Microsoft Defender Antivirus Service / WinDefend Service

### ISSUE THREAD

**Issue by adamshumpisxxx** [ionuttbara/windows-defender-remover#73]
Still running in Task Manager using up 200-250MB of RAM. I used the safe (N) option because the (Y) option breaks Microsoft Store / UWP / Apps. Can we somehow stop the WinDefend service? Thank you.

Windows 10 IoT Enterprise LTSC 21H2 (OS Build 19044.3208)

**Comment by adamshumpisxxx** [comment]
Solution:

Boot into Safe Mode, open Registry Editor, navigate to "Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WinDefend", find the Start DWORD, change it to a 4 and restart. WinDefend stays stopped. A quick note: the Start DWORD changes to a 3 upon reboot. Perhaps changing directly to a 3 is the way to go?

**Comment by ionuttbara** [comment]
The solution is removing the WinDefend from registry. Changing to 3 and reboot, nothing happens. The service will run normally without problems. 
You can run the script and press N, and the app is doing for you.
These can be restored.

**Comment by iam-thedude** [comment]
@adamshumpisxxx hi!

Thanks for your info!

But unfortunately, it didn't work for me. The service is still running. 
And Start DWORD changed to "2" after reboot from safe mode.

I also used "N" option via 12.5.1 version.

**Comment by iam-thedude** [comment]
Quick update.

Also tried changing Start DWORD to "3" in Safe Mode and after rebooting it changed to "2".

**Comment by iam-thedude** [comment]
Quick update №2.

Disabling WinDefend service using Autoruns in safe mode + changing Start DWORD to "4" didn't help too.

**Comment by ionuttbara** [comment]
remove the folder C:\Program Files\Windows Defender with IoBit Unlocker and it will work. (Disable Realtime Protection first)

**Comment by ionuttbara** [comment]
and C:\ProgramData\Microsoft\Windows Defender (or Windows Security) if that is not working

**Comment by iam-thedude** [comment]
@ionuttbara hi!

Will deleting these folders break UWP/MS Store apps?
And could this be reverted? I mean, if i need Denfender in future could I re-install it?

Thanks!

**Comment by iam-thedude** [comment]
@adamshumpisxxx hi!

Thanks for your reply!

As I wrote above, I tried changing DWORD in Safe Mode but after rebooting into Normal Mode this DWORD is changing to default (enabled) status and thus Antimalware Service Executable is still running.

BTW i'm running W11 Pro 22621.2134 (latest stable build).

**Comment by adamshumpisxxx** [comment]
> @adamshumpisxxx hi!
> 
> Thanks for your reply!
> 
> As I wrote above, I tried changing DWORD in Safe Mode but after rebooting into Normal Mode this DWORD is changing to default (enabled) status and thus Antimalware Service Executable is still running.
> 
> BTW i'm running W11 Pro 22621.2134 (latest stable build).

Then I'm not sure why you're trying a solution for Windows 10 (in my specific case Windows 10 IoT Enterprise LTSC 21H2 OS Build 19044.3324). You will likely need to fix this in a completely different way.

**Comment by adamshumpisxxx** [comment]
@iam-thedude  Perhaps this may be a good start:

https://www.elevenforum.com/t/using-regedit-to-disable-windows-defender-in-windows-11.6281/

Screenshot:

https://imgur.com/a/Cyzu0OE

**Comment by iam-thedude** [comment]
@adamshumpisxxx thanks!

These links could be useful.

But I managed to disable WinDefend service using this guide - https://www.alphr.com/disable-windows-defender-windows-11/
So, I changed Group Policy Settings only.

So, possible solution for W11 Pro 22621.2134 is using "N" method via 12.5.1 and disabling Group Policy Settings.
If something goes wrong, then it's time for woodoo stuff with regedit/autoruns/safe mode etc.

**Comment by adamshumpisxxx** [comment]
> @adamshumpisxxx thanks!
> 
> These links could be useful.
> 
> But I managed to disable WinDefend service using this guide - https://www.alphr.com/disable-windows-defender-windows-11/ So, I changed Group Policy Settings only.
> 
> So, possible solution for W11 Pro 22621.2134 is using "N" method via 12.5.1 and disabling Group Policy Settings. If something goes wrong, then it's time for woodoo stuff with regedit/autoruns/safe mode etc.

That would be the same advice I posted above at this address:

https://superuser.com/questions/947873/disable-windows-defender-in-windows-10

Screenshot:

https://imgur.com/kNMjbt8

Glad you got it figured out.
