### ISSUE TITLE
Lacking instructions

### ISSUE THREAD

**Issue by tulgaway** [ionuttbara/windows-defender-remover#74]
This tool is lacking instructions. We need instructions as to how to properly use it. DefenderRemover.exe does not even disable WinDefender. MsMpEng.exe is still running in the background after selecting N  ( I did turn off tamper protection prior to this) but ended up messing up Win Security app.

**Comment by ionuttbara** [comment]
Ok. I'll work on documentation when i have time.

**Comment by tulgaway** [comment]
at least tell us what/how to do if we already have win defender running? like do we have to turn off the tamper protection first and run this in safe boot in windows ? if it's just ran as a administrator, it does not disable anything.

**Comment by ionuttbara** [comment]
nothing. Run the app and select the desired option. For now disablation of tamper protection is not necessary.

**Comment by tulgaway** [comment]
what does "webthreatdefsvc" do? this one stays running after disabling win defender? also if mpssvc is disabled(cuz using 3rd party firewall within avast), win store breaks in my case is there way to turn it off without breaking winstore?

**Comment by ionuttbara** [comment]
defender phishing protection (not smart screen) and its not the firewall

**Comment by TDWillingham** [comment]
I found it pretty simple and straightforward.  Works like a charm so far.

**Comment by tulgaway** [comment]
> I found it pretty simple and straightforward. Works like a charm so far.

Really? It looks like it but that defender.exe does not turn off win defender for me for whatever reason but them registry files seems to work via powerrun

**Comment by TDWillingham** [comment]
Yeah, worked well on a new install for me.  Saved a nice chunk of memory.

**Comment by ionuttbara** [comment]
> 
Written a question in home page of script.
## 🛑 If i have a clean installed Windows with no updates the script is works, why in updated Windows the script is not working?

Updated Windows includes a ``` Windows Intelligence Update ``` this is designed for blocking actions , modifying Windows defender/Security Polocies, and so on. 
If the script is not work for you, first check if you have the Windows Security Intelligence Update installed. If you have, disable tamper protection, and re-apply the script
