### ISSUE TITLE
Error in ISOCreator.cmd

### ISSUE THREAD

**Issue by zbezj** [ionuttbara/windows-defender-remover#77]
There are some errors, the execution will report errors

1.please change   set "index=%index%"  to  set "index=! index!"

The last line：
2.please change   "defenderRemovedISO"  to "defenderRemoverWork"

**Comment by zbezj** [comment]
del c:\defenderRemoverImage\sources\install.wim
	ren c:\defenderRemoverImage\sources\install2.wim install.wim

**Comment by ionuttbara** [comment]
iso creator is deprecated and i don't have any plans to revive it for now. so i will close that now.
