### ISSUE TITLE
'nsudolc.exe' can not found in 12.5.1

### ISSUE THREAD

**Issue by xin2014** [ionuttbara/windows-defender-remover#78]
![image](https://github.com/ionuttbara/windows-defender-remover/assets/7124907/c011578f-7ea4-4207-81d3-ccee70c5363a)
![image](https://github.com/ionuttbara/windows-defender-remover/assets/7124907/614b0c63-4d22-494c-aafb-c6942a6afa4f)

**Comment by ionuttbara** [comment]
redownload the release. This should work now.
