### ISSUE TITLE
Defender Remover didn't work on W11 after CU 2023-08 

### ISSUE THREAD

**Issue by MysticFoxDE** [ionuttbara/windows-defender-remover#79]
Hi Ionut,

my W11 workstation installed CU 2023-08 by itself last night.
After that, the defender was reactivated by itself. 😭

Then I ran the latest version of your defender remover over it ...

![REFENDER REENABLED AFTER CU](https://github.com/ionuttbara/windows-defender-remover/assets/123583045/12c64b30-a6ab-4492-85cc-5cffcc63b82c)

... however, the Defender remained active afterwards. 😬

When running the exe, there were also a few errors, but I couldn't take a screenshot of them because the computer started nine shortly after they appeared.

Best Regards from Germany
Alex

**Comment by MysticFoxDE** [comment]
Hi Ionut,

I just ran the defender remover again to be on the safe side, but the defender still remains active after CU 2023-08. 😬

![REFENDER REENABLED AFTER CU 01](https://github.com/ionuttbara/windows-defender-remover/assets/123583045/6e40db39-a2e9-44c7-b640-8864d8887372)

Best Regards from Germany
Alex

**Comment by eleius** [comment]
I also noticed Defender Remover didn't work on a freshly installed Windows 10 ltsc with all recent updates installed. It didn't report any error but Defender is still active after reboot (tried with both the defender-only option and the defender + security services option). It worked fine when I used it last month.

**Comment by MysticFoxDE** [comment]
Hi @eleius,

> I also noticed Defender Remover didn't work on a freshly installed Windows 10 ltsc with all recent updates installed. It didn't report any error but Defender is still active after reboot (tried with both the defender-only option and the defender + security services option). It worked fine when I used it last month.


I found a small workaround.
If you deactivate the tamper protection on the Defender beforehand, the Defender Remover will work again. 😁

Best Regards from Germany
Alex

**Comment by tulgaway** [comment]
> Hi Ionut,
> 
> I managed now to get a screenshot of the errors ...
> 
> ![REFENDER REENABLED AFTER CU ERRORS](https://user-images.githubusercontent.com/123583045/259339623-9ae96857-5432-4826-8458-d35c8c13259a.jpg)
> 
> ... but as I see it, it's the same error four times in a row.
> 
> Best Regards from Germany Alex

the same errors here with schtask error and it does not disable any win services (of course with tamper protection off and tried even with everything off).  And I have bee telling the dude it's lacking instructions but he claimed it's just click and go lol.
Here is a screenshot after running DefenderRemover.exe once

<img width="601" alt="Screenshot 2023-08-11 145943" src="https://github.com/ionuttbara/windows-defender-remover/assets/136381089/625260c6-504f-4c25-ad33-8b9c11a47e7a">

**Comment by eleius** [comment]
> If you deactivate the tamper protection on the Defender beforehand, the Defender Remover will work again.

Unfortunately even with tamper protection disabled it doesn't work for me. It just throws a few very quick error messages I can't read and reboots my system, leaving Defender enabled.

(I tried starting the exe from a terminal to be able to read those messages, but it opens its own window and then clears everything when finished.)

**Comment by Belgorodski** [comment]
Hi, at the time of 22621.2134 Defender Remover is working properly after disabling all the switches on the page with protection systems.

After disconnecting, error windows appear, and then the system is rebooted by the program itself.

> ![image](https://github.com/ionuttbara/windows-defender-remover/assets/88776863/fcb923f9-92f3-4683-9171-2f4442ab433e)

The only thing that remains is an error that appears in some cases in the form of a notification on the desktop from the "Security and Maintenance Center".

>  ![image](https://github.com/ionuttbara/windows-defender-remover/assets/88776863/0164a314-a473-4def-9f0b-68a81d409000) 
Enable Windows Security Service
The Windows Security Center service is disabled. To enable it, click or tap here.

**Comment by ionuttbara** [comment]
disable notification

> Hi, at the time of 22621.2134 Defender Remover is working properly after disabling all the switches on the page with protection systems.
> 
> After disconnecting, error windows appear, and then the system is rebooted by the program itself.
> 
> > ![image](https://user-images.githubusercontent.com/88776863/260242332-fcb923f9-92f3-4683-9171-2f4442ab433e.png)
> 
> The only thing that remains is an error that appears in some cases in the form of a notification on the desktop from the "Security and Maintenance Center".
> 
> > ![image](https://user-images.githubusercontent.com/88776863/260242629-0164a314-a473-4def-9f0b-68a81d409000.png)
> > Enable Windows Security Service
> > The Windows Security Center service is disabled. To enable it, click or tap here.

disable Windows Security Center from Settings.

**Comment by eleius** [comment]
@ionuttbara since disabling was not working for me, I used the "Y" option to remove Defender and Security Components. It worked, but I noticed you're going to release a new version in the future with a "safe" method which I'd like to try.
Is there a way to undo the "Y" removal option without a restore point?

**Comment by ionuttbara** [comment]
added disalation of Windows Security Center in 12.6. test it. Also explorer crashes.
