### ISSUE TITLE
error

### ISSUE THREAD

**Issue by asukasika** [ionuttbara/windows-defender-remover#81]
After using the delete function, the Microsoft Store's built-in applications (Notepad, Xbox Gamebar, Windows Terminal) cannot be used. Please install

**Comment by ionuttbara** [comment]
it is Windows 11 or Windows 10 22H2?

**Comment by StenApp** [comment]
Probably related to this #83, since i cannot use foto viewer too.

**Comment by ionuttbara** [comment]
this is points to #83. i will close this because of duplication.

**Comment by asukasika** [comment]
Is win11 22H2

**Comment by Leslie00120** [comment]
After pressing the R button，my  Windows defender is uninstalled successfully.But my start menu doesn't work anymore. 
Version:window 11 23h2

**Comment by ionuttbara** [comment]
read #98.
