### ISSUE TITLE
0x80070057 - Errors when updating store apps

### ISSUE THREAD

**Issue by StenApp** [ionuttbara/windows-defender-remover#83]
I removed the Defender and getting errors in Store now.
Using Win11 2H2 august update.
<img width="691" alt="Screenshot 2023-08-22 140755" src="https://github.com/ionuttbara/windows-defender-remover/assets/32524257/1a671160-535c-42b3-9ed9-8b41e250f11f">

**Comment by iam-thedude** [comment]
Hi!

In your case you need to upgrade Windows in-place with option to "Keep your personal files and apps" on.
And then check this https://github.com/ionuttbara/windows-defender-remover/issues/80

**Comment by 2499083901** [comment]
Have you solved it? I have the same problem

**Comment by ionuttbara** [comment]
update of the issue:
it appears on Windows 10 22H2 in lastest version, so a fix/revert for that is coming soon!

**Comment by StenApp** [comment]
> update of the issue:
> it appears on Windows 10 22H2 in lastest version, so a fix/revert for that is coming soon!

Should i wait for your fix or inplace-upgrade?

**Comment by ionuttbara** [comment]
you can do in-place upgrade, and remove with safe methods.
 i don't have an ETA for that. In Windows 10 the problem appears and it fixed, in Windows 11, its a bit conplicated. i installed in vm and personal machine  but it works, i dont get any error.

**Comment by 2499083901** [comment]
What do I do if I want to upgrade

**Comment by StenApp** [comment]
> What do I do if I want to upgrade

https://pureinfotech.com/reset-pc-keeping-personal-files-windows-11/#resetthispc_keepmyfiles_local_reinstall_windows11

**Comment by 2499083901** [comment]
Thank you very much

**Comment by ionuttbara** [comment]
a solution to solve UWP problem is to change value of EnableLUA policy from 0 to 1. This will enable UAC. 
Microsoft broke UWP apps when UAC are disabled in Windows 11. It will be add in the script documentation soon.

**Comment by StenApp** [comment]
> a solution to solve UWP problem is to change value of EnableLUA policy from 0 to 1. This will enable UAC.
> Microsoft broke UWP apps when UAC are disabled in Windows 11. It will be add in the script documentation soon.

I tried to set UAC to 1 but it didn‘t help

**Comment by ionuttbara** [comment]
After months of debugging and bug hunting i've found the cause of problem
smartscreenps.dll is removed and unregistered by script. just copy the file from original DVD/ISO of Windows which you installed, also register with regsvr. the class {A463FCB9-6B1C-4E0D-A80B-A2CA7999E25D} is came from smartscreenps.dll so, in 12.6 the smartscreenps.dll is not removed anymore. also i can't restore that dll with the script, so for testing, it needs a clean machine , appling the script and reinterpretate that actions. After i get read to logs and more, and results of tests will be same , so this will help to solve this issue. i will close this in next 2 weeks if i get responses to close or no responses.

**Comment by zyr3344** [comment]
> After months of debugging and bug hunting i've found the cause of problem smartscreenps.dll is removed and unregistered by script. just copy the file from original DVD/ISO of Windows which you installed, also register with regsvr. the class {A463FCB9-6B1C-4E0D-A80B-A2CA7999E25D} is came from smartscreenps.dll so, in 12.6 the smartscreenps.dll is not removed anymore. also i can't restore that dll with the script, so for testing, it needs a clean machine , appling the script and reinterpretate that actions. After i get read to logs and more, and results of tests will be same , so this will help to solve this issue.

Will this modification restore smartscreen?

**Comment by ionuttbara** [comment]
as i said, the script is not restoring the files because are multiple versions of Windows. so you can do with sfc /scannow and after that registering smartscreenps.dll with regsvr32. reboot and try again.

**Comment by StenApp** [comment]
I used 12.6 with U option on my Win 11 23H2 build 22631.2715:

<img width="770" alt="Screenshot 2023-11-24 190829" src="https://github.com/ionuttbara/windows-defender-remover/assets/32524257/3bc7ddf7-db3d-49b8-8e88-e58d18c59436">

**Comment by ionuttbara** [comment]
disabled DCOM harms your system.. maybe the version of Windows is broken or something.. for my confirmation, have you tested on clean install or used installation? can you send me there evtx files (event logs) i want to investigate more. (the U is removing normal but without C:\Program Data\Microsoft\Windows Defender folder because that folder is needed for Windows App SDK Desktop and file explorer. Removing in Windows 23H2 and Canary (Dev Channel unaffected) will restore to Windows 10 Explorer, Task Manager and Desktop (Desktop is not existing)..

**Comment by StenApp** [comment]
> disabling DCOM harms your system.. maybe the version of Windows is broken or something.. for my confirmation, have you tested on clean install or used installation? can you send me there evtx files (event logs) i want to investigate more. (the U is removing normal but without C:\Program Data\Microsoft\Windows Defender folder because that folder is needed for Windows App SDK Desktop and file explorer. Removing in Windows 23H2 and Canary (Dev Channel unaffected) will restore to Windows 10 Explorer, Task Manager and Desktop (Desktop is not existing)..

I used a clean install. Disabled services and dcom and afterwards i used the defender remover with U option. As for the logs i mist look if i haven‘t deleted them yet.

**Comment by cherub0507** [comment]
> > After months of debugging and bug hunting i've found the cause of problem smartscreenps.dll is removed and unregistered by script. just copy the file from original DVD/ISO of Windows which you installed, also register with regsvr. the class {A463FCB9-6B1C-4E0D-A80B-A2CA7999E25D} is came from smartscreenps.dll so, in 12.6 the smartscreenps.dll is not removed anymore. also i can't restore that dll with the script, so for testing, it needs a clean machine , appling the script and reinterpretate that actions. After i get read to logs and more, and results of tests will be same , so this will help to solve this issue.经过几个月的调试和错误搜寻，我发现问题的原因smartscreenps.dll被脚本删除并取消注册。只需从您安装的 Windows 的原始 DVD/ISO 中复制文件，也可以注册 regsvr。类 {A463FCB9-6B1C-4E0D-A80B-A2CA7999E25D} 来自 SmartScreenps.dll因此，在 12.6 中，SmartScreenps.dll 不再被删除。此外，我无法使用脚本恢复该DLL，因此对于测试，它需要一台干净的机器，应用脚本并重新解释该操作。在我读取日志等之后，测试结果将是相同的，所以这将有助于解决这个问题。
> 
> Will this modification restore smartscreen?此修改会恢复 smartscreen 吗？

face the same problem when update apps in MS store. 
tried reinstall some apps after uninstalled but failed.
warning code ‘0x80073CF9’. 
version 12.6 used only.
win 11 pro 23H2.
I wonder what should I do then.

**Comment by asukasika** [comment]
So has this issue been fixed or should we wait for updates

**Comment by cherub0507** [comment]
Cannot wait.
Re-install the Windows with option to "Keep your personal files and apps" on and fixed it.

**Comment by StenApp** [comment]
Any status on this issue?

**Comment by BxGz88** [comment]
"Keep your personal files and apps" ，The problem is still，0x80070057
