### ISSUE TITLE
Source Code Out of Sync with Release and Lack of Build Instructions

### ISSUE THREAD

**Issue by drunkwinter** [ionuttbara/windows-defender-remover#85]
Hi, I've been using this tool for a while now, but I have two concerns about this project:

1. **Source Code Mismatch**: The source code available in the repository doesn't seem to be in sync with the latest release and hasn't been updated in over a month now, making it difficult for us users to understand the changes made and to verify the source code of the executable.

2. **Lack of Build Instructions**: There are no documented build instructions or scripts provided in the repository, preventing users from compiling the executable themselves (I'm talking about the .exe here). This is important for transparency and the ability to build and verify the authenticity of the released binary.

**Comment by suspecting** [comment]
Bump. The batch code (which would be my save and grace) also doesn't have disable_def.bat. Strange.

**Comment by ionuttbara** [comment]
> Hi, I've been using this tool for a while now, but I have two concerns about this project:
> 
> 1. **Source Code Mismatch**: The source code available in the repository doesn't seem to be in sync with the latest release and hasn't been updated in over a month now, making it difficult for us users to understand the changes made and to verify the source code of the executable.
> 2. **Lack of Build Instructions**: There are no documented build instructions or scripts provided in the repository, preventing users from compiling the executable themselves (I'm talking about the .exe here). This is important for transparency and the ability to build and verify the authenticity of the released binary.

1. First i didn't have time for syncing the code information. The last version can be found by extracting the downloaded exe with 7-Zip or WinRAR.
2. The exe is an SFX Archive witch is including the content.
3. The disable_def.bat was introduced since 12.5.1 version. When i am updating to 12.6 version i'll sync all the code and put the updated documentation (with clearer instructions, and listed in which version of Win is working or not)

**Comment by drunkwinter** [comment]
Thanks for the information. I was looking if I somehow could contribute, but was put off when I saw the source was not in sync.

**Comment by ionuttbara** [comment]
now the code should be synced with .exe.
