### ISSUE TITLE
12.5.4 - Antimalware service executable still running

### ISSUE THREAD

**Issue by StenApp** [ionuttbara/windows-defender-remover#86]
I used 12.5.4 with option N and M.
Antimalware service executable is still running

<img width="646" alt="Screenshot 2023-09-03 140444" src="https://github.com/ionuttbara/windows-defender-remover/assets/32524257/d63f9ef4-b645-4cc3-aa10-ad3887b6c245">

**Comment by StenApp** [comment]
Sorry had a typo in the version 12.5.4

**Comment by ionuttbara** [comment]
i see that is a spelling error. it must work now in 12.5.5.
