### ISSUE TITLE
Binding for Enter key.

### ISSUE THREAD

**Issue by iiwwnnaa** [ionuttbara/windows-defender-remover#89]
I accidentally pressed Enter Key and defender is totally removed.
Is this kind of bugs? or normal
There is no choice for remove defender on menu
![image](https://github.com/ionuttbara/windows-defender-remover/assets/58810238/2384fc71-6d8b-4265-98a2-ecc1326f7b51)

**Comment by ionuttbara** [comment]
i take this to be a bug.

**Comment by ionuttbara** [comment]
fixed.
