### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by onlyoneeon** [ionuttbara/windows-defender-remover#90]
MsMpEng.exe Comes back right away.

**Comment by ivorget** [comment]
Same here, removed Defender and other security apps but after the reboot MsMpEng is running again. TamperProtection shows as still enabled in regedit.
Using Windows 10 Home 22H2.

**Comment by MysticFoxDE** [comment]
Hi @onlyoneeon,
Hi @ivorget,

before running the Defender Remover, please turn off TamperProtection and everything else listed on this settings page ...
https://www.techtarget.com/searchenterprisedesktop/tip/What-IT-should-know-about-Tamper-Protection-in-Windows-10

Best Regards from Germany
Alex

**Comment by ionuttbara** [comment]
turn off Tamper Protection if first attempt for removal is not working!
