### ISSUE TITLE
The process is still active after "N" option

### ISSUE THREAD

**Issue by p1k2i** [ionuttbara/windows-defender-remover#94]
![Screenshot_682](https://github.com/ionuttbara/windows-defender-remover/assets/47232701/f8407ad5-917b-4d4d-907c-5bf627f30399)

**Comment by pro100kryto** [comment]
![Screenshot_683](https://github.com/ionuttbara/windows-defender-remover/assets/47232701/6794a17c-89b6-4d5a-92c2-85f24341e448)
