### ISSUE TITLE
virtualizations based security still running after using (N) command 

### ISSUE THREAD

**Issue by vishalhoc** [ionuttbara/windows-defender-remover#96]
![image](https://github.com/ionuttbara/windows-defender-remover/assets/13188309/a86658b7-945b-4d7c-b946-d4357b50f2d6)

**Comment by ionuttbara** [comment]
its look like you use Hyper-V or WSL. so if you want to disable VBS and you are NOT Using Hyper-V or WSL,and the policies are not working  you must disable Microsoft Hyper-V Virtualization Infrastructure Driver from Device Manager and reboot. (the policies and values are automaticly reverted when Hyper-V or WSL are enabled).
