### ISSUE TITLE
antimalware service still active after N command

### ISSUE THREAD

**Issue by vishalhoc** [ionuttbara/windows-defender-remover#97]
![image](https://github.com/ionuttbara/windows-defender-remover/assets/13188309/416e8189-6a5d-492c-950e-6dc34ff2a84e)

**Comment by ionuttbara** [comment]
what version of Windows you have?

**Comment by vishalhoc** [comment]
> what version of Windows you have?
windows 11 latest dev version

**Comment by danik292** [comment]
I test it

**Comment by ionuttbara** [comment]
labeled as bug

**Comment by wongcc2012** [comment]
Hi. Found same issue here. I am using the "RTM official release"  23H2 22631.2428
the antivirus service is UP, and still removing the virus files (test eicar file in my case)

**Comment by ionuttbara** [comment]
ok. i will check.. maybe its a PowerRun issue, but 
Have you tried the script with Tamper Protection **disabled**?

**Comment by wongcc2012** [comment]
Hi.
When I tried to temporary turned protection off and tamper off, got below
error (it flashes very fast, hope can have the debug version without
disappearing )

[image: image.png]


Have a nice day
Regards,
Ken

**Comment by wongcc2012** [comment]
Hi I have just downloaded the latest version release 12.6 and FAILED to disable (option M or N)
I have manual paused the real time protection and tamper protection then run the program, a bunches of CMD window prompted out and the machine rebooted, after reboot the AV service is re-enabled. and EICAR test  / defender remover file identified as virus

Removing the Defender is NOT tried yet because I want a way back.

**Comment by ionuttbara** [comment]
re opened.

**Comment by ionuttbara** [comment]
ok, i get some clarification, you'll need to launch in safe mode to disable/enable defender using new methods 
first, download the script 
second go to safe mode using this command 
``` bcdedit /set {current} safeboot minimal ```
and reboot
third apply that method
and reboot.

**Comment by wongcc2012** [comment]
> ok, i get some clarification, you'll need to launch in safe mode to disable/enable defender using new methods first, download the script second go to safe mode using this command `bcdedit /set {current} safeboot minimal` and reboot third apply that method and reboot.

I have tried to use the command to enter safemode, but I can't do any setting in the windows security. It is a blank window.
![image](https://github.com/ionuttbara/windows-defender-remover/assets/111074201/2a7ea6da-b32a-416f-9100-888518bad2ad)

I tried to reboot again, but it stayed in safe mode and cannot go back to normal mode. Please advise.

**Comment by wongcc2012** [comment]
I have managed to enter safe mode (shift restart, safe mode) and run the utility and tried to disable the WIN DEF
however after reboot. seem the service is still running and I have no way to pause the protection

![image](https://github.com/ionuttbara/windows-defender-remover/assets/111074201/ac246026-fb48-4507-a98e-d9297068fd36)

**Comment by ionuttbara** [comment]
ok,

**Comment by rudolphos** [comment]
I'm using Windows 10 22H2, 19045.3803 and having the same problem after N option after restart, MsMpEng.exe still runs with 114 MB of ram usage.

![image](https://github.com/ionuttbara/windows-defender-remover/assets/4366810/cb845af6-f405-4fb7-a201-e6fde5e3ec2a)
