### ISSUE TITLE
After installing win update, taskbar is broken (search, win button and notifications)

### ISSUE THREAD

**Issue by StenApp** [ionuttbara/windows-defender-remover#98]
I'm really sad.

Everytime i use your very good tool to remove defender i run into the same problem.
One windows update later "everything" breaks after a restart to install.

I run Win 11 22H2 with security update 10/2023.
removed defender (used [second release of 12.5.6](https://github.com/ionuttbara/windows-defender-remover/releases/tag/release_def_12_5_6_2)) on 15.10.2023, installed the optional win update today and boom:

Taskbar malfunctions, windows button doesn't work, search bar at bottom does nothing and wifi/sound and battery button is broken too.

I'm running out of ideas what to do and what really causes this outage.

I can use the following commands but are unsure if this will half reinstall defender and break more.
`dism /online /cleanup-image /restorehealth`
`sfc /scannow`

Eventlog shows me some DCOM server couldn't be started:
[Errors.evtx.txt](https://github.com/ionuttbara/windows-defender-remover/files/13188513/Errors.evtx.txt)

**Comment by StenApp** [comment]
After a second restart my screen stays black with mouse cursor and takes long to load the gui.

- i opened ctrl+alt+esc to start taskmanager
- i executed both via Powershell:
`dism /online /cleanup-image /restorehealth`
`sfc /scannow`
- i removed defender again and restarted
- i looked in the eventlog and executed the ones that missed to get registered:
```
backgroundTaskHost.exe -ServerName:Global.RulesEngine.AppXgphnekvm0vv49drvfehh4b6kyf6ckafp.mca
backgroundTaskHost.exe -ServerName:Global.Accounts.AppXqe94epy97qwa6w3j6w132e8zvcs117nd.mca
backgroundTaskHost.exe -ServerName:Global.IrisService.AppXwt29n3t7x7q6fgyrrbbqxwzkqjfjaw4y.mca
backgroundTaskHost.exe -ServerName:Global.DesktopSpotlight.AppXz2j21w56bgxkgsjhtn7zkjsepq96erz2.mca
backgroundTaskHost.exe -ServerName:WebExperienceHost.AppXt2rk6m02ana976jna04hdq35jfnzy7f7.mca
backgroundTaskHost.exe -ServerName:App.AppXmtcan0h2tfbfy7k9kn8hbxb6dmzz1zh0.mca
```

now search runs, windows button (=menu) loads with large delay, no context menu on Taskbar icons and notifications is still broken

**Comment by rxybeleaua** [comment]
Hello, I have the same problem. It is the first time i stumbled upon this. I downloaded defender remover as windows downloaded it back and after using it everything was fine. Today when I decided to update my windows everything went down. Mine does the exact same things yours is doing.

**Comment by StenApp** [comment]
I looked up error codes here:
https://learn.microsoft.com/en-us/windows/win32/appxpkg/troubleshooting?redirectedfrom=MSDN

I tried the solution here with no luck:
https://learn.microsoft.com/en-us/answers/questions/880616/start-button-not-responding-outlook-will-not-conne?page=1#answers

Looked here with no luck:
https://answers.microsoft.com/en-us/windows/forum/all/start-button-search-bar-and-notifications-button/50f0e99c-3d8d-4c14-888f-18833a60474d

Going to reset Windows, a trillionst time

**Comment by ionuttbara** [comment]
noted as a bug

**Comment by ionuttbara** [comment]
ok, this is stupid. 
Why Windows App SDK needs C:\ProgramData\Microsoft\Windows Defender folder? in next release if you want to do that press 'U' instead of 'Y'. (in Windows 10 , and Windows 11 up to 23H2 'Y' is working).
Whitelistd ProgramData folders and here go to.

**Comment by StenApp** [comment]
Thanks for investigation.

You should report that issue in https://github.com/microsoft/WindowsAppSDK or on feedback hub.
Either it's an oversight or they better have an explanation

**Comment by ionuttbara** [comment]
this will help. maybe security reasons, but what happens when someone removes defender and installs Avast or Malwarebytes? because Microsoft made VBS which blocks removal of files of Defender not for System. its more easy to delete System32 Files than the executable of Windows Defender service.

**Comment by long45343** [comment]
Same bug.
how can I fix it?

**Comment by ionuttbara** [comment]
by restoring the foder Windows Defender folder from 1\Program Data\Microsoft\Windws Defender from a install.wim/esd from corresponding Windows ISO Image **OR** via reinstalling Windows and re-apply the script with U.

**Comment by long45343** [comment]
> by restoring the foder Windows Defender folder from 1\Program Data\Microsoft\Windws Defender from a install.wim/esd from corresponding Windows ISO Image **OR** via reinstalling Windows and re-apply the script with U.
Already Tried it but my start menu still dead like this:

and the recommend item(in chinese called"推荐的项目"returned empty. Quick Search(Windows + S or windows + Q)doesn't work.and the task bar will show later then get into the deskop
I use The lastest Version Of this software(12.6) yesterday and this issue appear when WIndows insider release a  new beta version an I update it. 
Or can I reinstalling my windows Without Clean my application any files?
I Tried mount the image and open setup.exe to cover the system files and tried to fixed it.But It doesn't work even the Windows defender works fine but my start menu and windows search still dead.

**Comment by StenApp** [comment]
https://github.com/microsoft/WindowsAppSDK/issues/4013#issuecomment-1858309973
