### ISSUE TITLE
Powerrun.exe is not compatible / not working

### ISSUE THREAD

**Issue by scornieller** [ionuttbara/windows-defender-remover#99]
I receive these errors and app does not work. Windows 10 32 bit

"PowerRun.exe is not compatible with the version you're running..."

![IMG_0827](https://github.com/ionuttbara/windows-defender-remover/assets/12589272/f4c2083f-fa8e-44bf-aca6-4c25894d7976)

**Comment by ionuttbara** [comment]
moved to superUser64.exe, but for x86 app untested, thx for information.
you are using x86 Windows, so the app is compatibile with x64 and ARM64, adding x86 support in next release.

**Comment by ionuttbara** [comment]
compiled a 32-bit in lastest release (12.6)
